### ISSUE TITLE
lookups.flatMap is not a function

### ISSUE THREAD

**Issue by CooLNuanfeng** [eslint/generator-eslint#100]
`yo eslint:plugin         
/Users/nuanfeng/.nvm/versions/node/v10.15.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`, `${prefix}/*/index.cjs`, `${prefix}/*/index.mjs`]),
TypeError: lookups.flatMap is not a function
`

**Comment by bmish** [comment]
Which version are you using? Note that `flatMap` requires Node 11+ and it looks like you're using Node 10.

**Comment by CooLNuanfeng** [comment]
node v10.15.3, i try node v11, thanks
