### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by bmish** [eslint/generator-eslint#137]
I think we are ready to release a patch version of generator-eslint with the current changes that have been merged already.

In addition, starting to prepare for a major version release (generator-eslint v4):
* #133
* #134
* #135
* #136

Regarding major version release timing:
* We could do a major release now/soon and then perform a minor release to upgrade the plugin template to ESLint v9 when that gets released in the coming months (get changes out sooner)
* Or we could wait until ESLint v9 is released (not strictly necessary but could do this to align the release schedule or ensure full preparedness for ESLint v9)

**Comment by nzakas** [comment]
I don’t think we need to plan too carefully for a major version of this package given that it’s not something people use all the time. If there’s stuff that’s good to get out, we can release a major update at any time.

**Comment by nzakas** [comment]
@btmills is planning on doing a release this weekend

**Comment by btmills** [comment]
v4 is out! https://github.com/eslint/generator-eslint/releases/tag/v4.0.0
