### ISSUE TITLE
When I use `yo eslint:plugin` ,  I get the following error:

### ISSUE THREAD

**Issue by wangrongding** [eslint/generator-eslint#139]
When I use `yo eslint:plugin` ,  I get the following error:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

<img width="728" alt="image" src="https://user-images.githubusercontent.com/42437658/193977052-c84c6dba-0d6f-44fa-ba95-156b12d7d5ac.png">

**Comment by bmish** [comment]
That doesn't look a problem with generator-eslint. I'm guessing you'll get the same error when you just type `yo` by itself. Does updating to the latest version help? `npm i -g yo`.

**Comment by wangrongding** [comment]
I tried to reinstall it but still have this problem.  

Main Information：
yo@4.3.0
node v16.16.0
macOS 13.0 Beta5

<img width="704" alt="image" src="https://user-images.githubusercontent.com/42437658/194075891-e9eb8d34-1e07-4ba6-bc49-73e10ceffcdb.png">

**Comment by bmish** [comment]
As I suspected, it looks like this is a general yo issue and the Mac OS beta you're on: https://github.com/yeoman/yo/issues/753

**Comment by snitin315** [comment]
Closing as it's not related to `generator-eslint`
