### ISSUE TITLE
should `eslint` be a devDependency or peerDependency?

### ISSUE THREAD

**Issue by cowchimp** [eslint/generator-eslint#18]
Hi.

http://eslint.org/docs/developer-guide/working-with-plugins
mentions that `eslint` should be defined in the `peerDependencies` section of your plugin's package.json.

However the yeoman generator adds `eslint` to the `devDependencies` section.
https://github.com/eslint/generator-eslint/blob/67ccdc5405d8850dc1fb467173ee31ac066eb64f/plugin/templates/_package.json#L19

Which is correct?

Thanks.

**Comment by ilyavolodin** [comment]
ESLint should be added to both. `peerDependencies` section would specify that plugin expects to be installed at the same level as ESLint, and `devDependencies` is for unittesting inside plugin itself.

**Comment by nzakas** [comment]
You can actually just use peerDependencies for this. Peer dependencies are installed like regular dependencies when developing from source

**Comment by platinumazure** [comment]
I know that peerDependencies is sufficient here, but for semantic accuracy, I think I agree with @ilyavolodin. Should we not try to keep the generated package.json semantically accurate?

**Comment by nzakas** [comment]
@platinumazure It's always a bad idea to have two references when one will do because there's the possibility of falling out of sync. Peer dependencies is all that's needed

**Comment by bmish** [comment]
Closing as obsolete at this point. I'm working on ensuring the generated plugin will have the latest dependencies for an upcoming major release soon.
