### ISSUE TITLE
Missing meta.messages property

### ISSUE THREAD

**Issue by MikeMcC399** [eslint/generator-eslint#181]
## Suggestion

Support the recommended rule [eslint-plugin/prefer-message-ids](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/prefer-message-ids.md) by providing a `meta.messages` property using a [MessageId](https://eslint.org/docs/latest/extend/custom-rules#messageids). Currently, running `yo eslint:rule` does not add this property to the generated `lib/rules/<rule-id>.js` rule.

## Background

- The rule [eslint-plugin/prefer-message-ids](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/prefer-message-ids.md) from [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) is part of the recommended config for this plugin where it says:

> When reporting a rule violation, it's preferred to provide the violation message with the messageId property instead of the message property.

## Documentation

- [MessageIds](https://eslint.org/docs/latest/extend/custom-rules#messageids)

**Comment by nzakas** [comment]
Thanks for the suggestion. Would you like to submit a PR to add this?

**Comment by MikeMcC399** [comment]
@nzakas 

> Would you like to submit a PR to add this?

I'm very new to ESLint and at this time I don't feel that I have the skills and experience to implement the suggestion. Sorry!

I just noticed the issue as I was working on resolving a lot of [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) upgrade issues which I started on one month ago.

**Comment by MikeMcC399** [comment]
@bmish 
> So you want to add `messages: {}` with an empty object I assume?

That would be a minimum and just adding that to the template would be easy to implement.

What I wasn't sure about is how far this should be extended, and if it should be expanded to a dialog which asks for a `messageID` and a message or assumes some default `messageID `and adds a dummy message. That's where my lack of experience in this area breaks down!

**Comment by bmish** [comment]
I don't think the generator needs to fill in any actual messages. The rule creator probably doesn't specific messages ready yet when they're just trying to create the barebones rule skeleton.

**Comment by MikeMcC399** [comment]
@bmish 

So I suggest to add:

```js
    messages: {} // Add messageId and message
```

to the template. The linting message will stay the same, however adding the above line into the template means that rule creators should be able to find the place faster, where they need to add a message. No additional information is requested at rule creation time with `yo eslint:rule`.

Linting error:

> error  `meta.messages` must contain at least one violation message      eslint-plugin/prefer-message-ids

If that sounds good, then I will submit a PR for this change.

**Comment by bmish** [comment]
That sounds reasonable.

**Comment by MikeMcC399** [comment]
@bmish 

Should this be a `chore` (no release), `fix` (patch release) or `feat` (minor release)?

It doesn't change any error message, so from that point of view it could be a `chore`. On the other hand it won't get used unless there is a release.

**Comment by bmish** [comment]
`feat` should be fine. It's not fixing anything, but it is a possible usability improvement.

**Comment by MikeMcC399** [comment]
- I've submitted #182 to resolve this issue. Thanks for the advice about what to add!
