### ISSUE TITLE
Generated plugin README has legacy config file reference

### ISSUE THREAD

**Issue by MikeMcC399** [eslint/generator-eslint#193]
## Current behavior

When `yo:eslint:plugin` is used to generate a new plugin, the `Usage` section of the generated `README.md` file says

> Add `name-of-plugin` to the plugins section of your `.eslintrc` configuration file.

and provides instructions to configure a [deprecated legacy configuration file](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated) `.eslintrc`.

## Expected behavior

When `yo:eslint:plugin` is used to generate a new plugin, the `Usage` section of the generated `README.md` file should provide instructions to configure a [current configuration file](https://eslint.org/docs/latest/use/configure/configuration-files), for example `eslint.config.mjs`, compatible with ESLint `v9`.

## Versions

| Component          | Version        |
| ------------------ | -------------- |
| Ubuntu             | `24.04.1` LTS  |
| Node.js            | `v20.18.0` LTS |
| npm                | `10.8.2`       |
| `yo`               | `5.0.0`        |
| `generator-eslint` | `5.1.0`        |

## Steps to repoduce

```shell
npm install yo@latest -g
npm install generator-eslint@latest -g
```

```shell
mkdir generator-eslint-test
cd generator-eslint-test
```

Execute `yo eslint:plugin` and accept defaults:

```text
$ yo eslint:plugin
? What is your name? Tester
? What is the plugin ID? template-test
? Type a short description of this plugin: Template test
? Does this plugin contain custom ESLint rules? Yes
? Does this plugin contain one or more processors? No
   create package.json
   create eslint.config.mjs
   create lib/index.js
   create README.md

Changes to package.json were detected.
Error detecting the package manager. Falling back to npm.

Running npm install for you to install the required dependencies.
npm warn ERESOLVE overriding peer dependency
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported

added 230 packages, and audited 231 packages in 4s

55 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by nzakas** [comment]
Yes, that should be updated. Do you want to submit a pull request?

**Comment by MikeMcC399** [comment]
@nzakas 

> Yes, that should be updated. Do you want to submit a pull request?

Yes, I will submit a PR for this.

**Comment by MikeMcC399** [comment]
- See PR #194 for resolution
