### ISSUE TITLE
Docs language change once the core rules are updated?

### ISSUE THREAD

**Issue by platinumazure** [eslint/generator-eslint#21]
@pedrottimark has been going through our rule documentation to try to standardize some of the language and structure. I assume that the `eslint:rule` generator should also be similarly updated, once some of the new standards have been fully established.

EDIT: Proposal for this issue is as follows:
* We should fix the generated .md files to use the preferred rule docs example callouts:
    * `Examples of **incorrect** code`
    * `Examples of **correct** code`

This allows for easier integration with core ESLint guidelines, and plugin authors can choose to use alternative language if they prefer.

**Comment by nzakas** [comment]
I'm not sure the changes would be noticeable in the template here. Do you have something in mind?

**Comment by pedrottimark** [comment]
The 2 example sentences are a simple change. I can make a pull request now if you like.

How much beyond that depends on the balance between providing more headings to be deleted if they are not needed versus leaving people to copy and paste parts they need from existing rule pages.

If you want to expand the scope of the template, I can provide some stats about patterns when we get to 80% of the distinguish examples process.

**Comment by nzakas** [comment]
The generator isn't just for use with ESLint, people also use it for custom rules. So whatever we put in the template should be generally appropriate.

**Comment by platinumazure** [comment]
@nzakas @pedrottimark I had originally opened this issue with the example sentences in mind-- seemed to me that we should have those align with core ESLint, since the generator can be used for core rule development. I have no real opinion on whether more sections should be included or not. I think that once @ilyavolodin finds the time to compile the rule docs style guide he's working on, it won't matter if we decide to omit new sections because we can always refer people to the style guide.

Oh, speaking of the style guide, maybe we should include a link to that in a comment in the generated .md file? Of course, that would require that we have a place we can link to in the first place. I can separate that out into a new issue if this gets closed before the style guide is complete.

**Comment by platinumazure** [comment]
@eslint/eslint-team I've edited the original post for this issue with a concrete proposal. Could we please evaluate?

Proposal is reproduced here for convenience:

* We should fix the generated .md files to use the preferred rule docs example callouts:
    * `Examples of **incorrect** code
    * `Examples of **correct** code

This allows for easier integration with core ESLint guidelines, and plugin authors can choose to use alternative language if they prefer.

**Comment by nzakas** [comment]
Fine by me.
