### ISSUE TITLE
Feature Request: Allow user to specify indentation size

### ISSUE THREAD

**Issue by iancmyers** [eslint/generator-eslint#22]
I know that the ESLint core project uses an indentation size of 4, however the world is a magically diverse place with many different indentation preferences.

Would you accept a PR that:

* On `yo eslint:plugin` prompted users for their preferred indentation size and generated an `.editorconfig` accordingly
* On `yo eslint:rule` prompted users for their preferred indentation size (if the rule is for a plugin) and generated files to that indentation size. It would default to the size specified in `.editorconfig`, if present.

**Comment by iancmyers** [comment]
Alternatively, on `yo eslint:rule`, the generator could just adhere to the `.editorconfig`, if one is available and _not_ prompt the user.

**Comment by nzakas** [comment]
No, I'm sorry. You can always use ESLint's autofix or your editor to make this change. This is far beyond the scope of this generator. It's intended as a starting point for you to modify.

**Comment by iancmyers** [comment]
@nzakas I hope you'll reconsider the PR I made. The PR only has the JavaScript generated adhere to an `.editorconfig`, if present, without any prompting or additional overhead to the user.

I understand that this generator is a starting point. I believe that having the tool respect a commonly used config makes it a _better_ starting point for users. Many plugins use `.editorconfig` settings that are different from what is currently generated (`eslint-plugin-react`, for example). I understand that I can go in and have my editor fix this each time I generate a new rule. I think it would be better if I didn't have to fight the tool and it did the right thing.

**Comment by iancmyers** [comment]
I've updated this issue to better reflect the scoped-down request and what was was PR'd in #24.
