### ISSUE TITLE
adding .eslintrc

### ISSUE THREAD

**Issue by oriSomething** [eslint/generator-eslint#3]
- it can be useful.
- the default settings of ESLint disallow `global-strict`, so it can useful

**Comment by nzakas** [comment]
I'm sorry, I don't understand what you're asking. Can you explain further?

**Comment by oriSomething** [comment]
after `yo eslint:rule` finished and i start to code, the code editor shows me eslint warnings / errors, because the default eslint's settings do not allow `global-strict` for example.
fixing it, it's by adding `.eslintrc` file with match rules. so it can be a nice addition to generate `.eslintrc` default file for this project

**Comment by nzakas** [comment]
Ah I see. I'd prefer to let people create their own .eslintrc. They might not like the settings we setup, and most people end up copying their own .eslintrc into projects they create.
