### ISSUE TITLE
Generator hangs after generating files

### ISSUE THREAD

**Issue by platinumazure** [eslint/generator-eslint#30]
I'm on Windows running a bash-like shell, so it's probably a weird setup. But I wanted to open this in case there was something we could do in code to mitigate this. For example, if we aren't calling inquirer's callback, that can appear to hang on some platforms.

In terms of functional impact, there is none-- files are generated and I just have to sigint the process. But if that's preventable, all the better, right?

I'll investigate this-- just wanted to put this out here in case anyone had any insights.

**Comment by ilyavolodin** [comment]
Not a weird setup at all. The whole ESLint team is using that setup with exception of 2-3 people (as far as I know). Last time I ran generator, everything worked fine for me, although it change since then. Can you provide more information about what seems to be the problem?

**Comment by platinumazure** [comment]
@ilyavolodin Thanks for responding. Everything works fine except that the process hangs after it creates the files, rather than terminating. That's why I was guessing it had to do with failing to call a callback (either inquirer or something else).

I also have an issue where inquirer itself does not respond to arrow keys, but that's the same problem as in `eslint --init` and I am able to work around that by typing in numbers and pressing Enter. I only mention this in case it's somehow related to the thing I'm actually reporting (I'm well aware that the interactivity issue is a Windows+Node+Inquirer problem that we have little to no control over).

I think I've provided all I can, but is there anything else you would like me to provide?

**Comment by platinumazure** [comment]
Aw, hell. `eslint --init` also hangs when it's done. I think this is an upstream issue after all. Sorry for wasting your time.
