### ISSUE TITLE
Should generator-eslint have a main file?

### ISSUE THREAD

**Issue by platinumazure** [eslint/generator-eslint#31]
Hi folks, I was looking at the package.json when I noticed that there was a "main" entry pointing to "app/index.js". That file doesn't exist. Furthermore it seems Yeoman uses some magic to read the filesystem and gather what it needs to know.

Since neither the user nor Yeoman needs to read a main file, should it be removed?

**Comment by zxqfox** [comment]
I was confused when `yo eslint` didn't showed after installation in `yo` menu ;-( Not sure if it's about main file.

I'd prefer something like: https://github.com/yeoman/generator-angular/blob/master/app/index.js

**Comment by nzakas** [comment]
We can either remove it, or if someone wants to implement it, that's fine too. I didn't implement it because it would have to ask what you want to create and then delegate to one of the other generators, and I figured it was easier for people to just type `yo ESLint:rule`.

**Comment by platinumazure** [comment]
Ah, gotcha.

I'll look into creating a PR (but I'm fairly sure this is a low priority
for both of us). Thanks for your reply.

**Comment by platinumazure** [comment]
@nzakas Do you have a preference, between removing the main entry or implementing it properly?

**Comment by nzakas** [comment]
I think removing it is fine unless someone really wants to implement it.

**Comment by platinumazure** [comment]
I've got an implementation nearly ready, just need to write unit tests. I'll try to have a PR this weekend.

**Comment by platinumazure** [comment]
No forward progress since my last update, but again it's only a few unit tests away from a PR. I'm preparing to move house so my free time these days is unpredictable; thus I will not commit to a date within the month. Thanks for your patience.

**Comment by platinumazure** [comment]
Haven't forgotten this, but unfortunately no forward progress since the last update.

**Comment by platinumazure** [comment]
Resumed work on this. Hoping to finish this week, along with the other issue I committed to.

**Comment by platinumazure** [comment]
@nzakas @zxqfox Finally have a PR ready for this. I tested locally with `npm link` and it seems to work fine, but it would be good to get more eyes on this. Thanks!
