### ISSUE TITLE
Should we remove node 0.10, 0.12 from TravisCI config?

### ISSUE THREAD

**Issue by platinumazure** [eslint/generator-eslint#39]
ESLint no longer supports Node versions less than 4.x and has removed 0.10 and 0.12 from its Travis config. Should we do the same?

Note that this issue will block any transition to ES6 in this repo (without using a transpiler).

**Comment by nzakas** [comment]
We didn't officially remove support for this utility even though we did for ESLint itself. I don't see a problem with doing it here, we just need to make it a breaking change.

**Comment by platinumazure** [comment]
I'm taking that as an accept as long as we add a breaking label. I've added the label to the issues config for this repo, and I've added the label here. Thanks!

**Comment by Aladdin-ADD** [comment]
eslint v5 require node>=6.x, should we consider drop node v4 in 2.0.0?

**Comment by snitin315** [comment]
Fixed in `main` 
https://github.com/eslint/generator-eslint/blob/85082323e51706843ba1a8cb942709d5372f2c97/package.json#L53

https://github.com/eslint/generator-eslint/blob/85082323e51706843ba1a8cb942709d5372f2c97/.github/workflows/ci.yml#L28
