### ISSUE TITLE
Upgrade yeoman-generator to latest

### ISSUE THREAD

**Issue by platinumazure** [eslint/generator-eslint#43]
I'd like to upgrade yeoman-generator to latest. We're depending on yeoman-generator `^0.22.5`, but the latest is 0.24.1. Due to how semver ranges work, `^0.22.5` only picks up later patch releases, not later minor releases (due to major version being 0).

Reasons I want to do this:
1. It's always great to use latest software
2. Opportunity to rewrite prompt hooks to use promises instead of async callbacks (though I'll check node.green first)
3. Inquirer (dependency of yeoman-generator) is also updated to use 1.x (instead of 0.11), so should be a much improved experience.

The last point is potentially important for #42. We have an issue where single quotes in user input are being transformed into double quotes. I have no solid lead on why this is, but one possibility comes from Inquirer changing its dependencies between 0.11 and 1.x. They removed "readline2" in favor of Node's core readline. So I'd like to upgrade to see if the quote transform issue goes away as a result.

**Comment by nzakas** [comment]
Go for it. You can also just open a PR for this instead of an issue. :)

**Comment by platinumazure** [comment]
I use issues as notes-to-self sometimes, especially on repos I'm not
frequently on. Thanks for the tip though.

**Comment by nzakas** [comment]
Noted, just keep in mind that every issue you file triggers notifications to everyone.

**Comment by platinumazure** [comment]
Unfortunately it looks like this requires dropping support for Node 0.10 (yeoman-generator internally now uses Promises without supporting the old-style `this.async()` approach, and node.green says promises don't work on Node 0.10). Adding "breaking" label and deferring this for now.
