### ISSUE TITLE
Add support for ESLint configs

### ISSUE THREAD

**Issue by j-f1** [eslint/generator-eslint#62]
[lemonmade/generator-eslint-config](https://github.com/lemonmade/generator-eslint-config) is a Yeoman generator for ESLint configs. I opened https://github.com/lemonmade/generator-eslint-config/issues/1 to discuss merging the two projects together, but I haven't gotten a response. What do you think about including @lemonmade’s code in this project?

**Comment by not-an-aardvark** [comment]
How does this compare to `eslint --init`? It seems like we effectively already have a generator for ESLint configs.

**Comment by j-f1** [comment]
@not-an-aardvark `generator-eslint-config` generates `eslint-config-*` packages, not a config file for your project.

**Comment by not-an-aardvark** [comment]
That makes sense, although an `eslint-config-*` package is basically just a JavaScript config file called `index.js` rather than `.eslintrc.js`. I suppose it could be useful for a tool to create that automatically, though.

**Comment by lemonmade** [comment]
Yeah, that generator is not particularly complicated, I'd be perfectly fine with having any part of the code absorbed into this project, though.

**Comment by nzakas** [comment]
We are going to split out `—init` into its own package to use as a generator, so we won’t be adding it in this package.
