### ISSUE TITLE
Not compatible with recent Node versions (not compatible with got@5.7.1)

### ISSUE THREAD

**Issue by jleeothon** [eslint/generator-eslint#63]
Here is the output after trying to install with Node 8.11.1. If I understand correctly, it is because this is using a fairly outdated version of [`got`](https://www.npmjs.com/package/got)).

```
❯ npm i -g generator-eslint

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"8.11.1","npm":"5.6.0"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"5.6.0","node":"8.11.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/othon/.npm/_logs/2018-04-01T18_42_39_617Z-debug.log
```

**Comment by platinumazure** [comment]
Hi @jleeothon, thanks for the issue.

We definitely need to upgrade the dependencies and modernize the codebase. We currently support Node versions as far back as 0.12 (maybe 0.10), which is unnecessary.

I'm hoping to do a few upgrades and cut a major release for Node 6+ in the next week or two. Along those lines, if you are willing to submit any PRs to do simple dependency upgrades, we would really appreciate it. Thanks!

**Comment by jleeothon** [comment]
Thanks for the extra info, @platinumazure. I'm relatively new to Node, so bear with me :) I'll try to submit something around next week.

**Comment by bmish** [comment]
This ticket looks obsolete. [v2](https://github.com/eslint/generator-eslint/releases/tag/v2.0.0) should work on Node 8. We will also be releasing a new major version targeting the latest versions of Node in the near future.
