### ISSUE TITLE
[docs] let's explain in readme the questions that this CLI will ask

### ISSUE THREAD

**Issue by revelt** [eslint/generator-eslint#70]
This CLI will ask the following questions:

> Does this plugin contain custom ESLint rules?

Let's explain in the readme, what is not a custom ESLint rule and how it differs from a custom-one.

> Does this plugin contain one or more processors?

Let's explain in the readme, what are the processors, what they do? Which ones are available? Mind you, the ESLint documentation mentions only custom formatters and custom parsers, there is no mention of processors. Let's explain what those are.

**Comment by nzakas** [comment]
As always, pull requests with documentation updates are appreciated!
