### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by nzakas** [eslint/generator-eslint#86]
This package is quite old and it’s been a while since it’s been updated. We should go through and upgrade all dependencies to their most recent versions.

eslint-release and yo in particular must be upgraded.

**Comment by bmish** [comment]
I'd be happy to tackle this and all the other improvements needed before the release. I'll work on it in the next week or so.

**Comment by nzakas** [comment]
Awesome, thanks so much.

**Comment by bmish** [comment]
I have PRs open to update all dependencies except for the yeoman dependencies. I'll work on the yeoman dependencies in the coming days.
